version: "3"

tasks:
  debug:
    desc: Debug
    cmds:
    - cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
    - cmake --build build
    - cmake --install build
    - gdb ./bin/main

  build:
    desc: Build 
    cmds:
    - cmake -S . -B build
    - cmake --build build

  run:
    desc: Run 
    cmds:
    - cmake --install build
    - ./bin/main
