version: "3"

tasks:
  debug:
    desc: Build program in Debug 
    cmds:
    - cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
    - cmake --build build
    - cmake --install build


  debugger:
    desc: Run program in debugger
    cmds:
    - task: debug
    - gdb ./bin/main

  build:
    desc: Build 
    cmds:
    - cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
    - cmake --build build

  run:
    desc: Run 
    cmds:
    - task: build
    - cmake --install build
    - ./bin/main

  test:
    desc: Build/Run tests
    dir: ./build
    cmds:
      - task: debug
      - ctest --rerun-failed --output-on-failure {{ .CLI_ARGS }}
