version: "3"

tasks:
  debug:
    desc: Debug
    cmds:
    - cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
    - cmake --build build
    - cmake --install build
    - gdb ./bin/main

  build:
    desc: Build 
    cmds:
    - cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
    - cmake --build build

  run:
    desc: Run 
    cmds:
    - task: build
    - cmake --install build
    - ./bin/main

  test:
    desc: Build/Run tests
    dir: ./build
    cmds:
      - task: build
      - ctest
